/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

#ifdef LOCAL
#define debug(...) cerr << "[" << #__VA_ARGS__ << "]:", debug_out(__VA_ARGS__)
#else
#define debug(...) 42
#endif

vector<string> split(string &s, string delimiter) {
    size_t pos_start = 0, pos_end, delim_len = delimiter.length();
    string token;
    vector<string> res;

    while ((pos_end = s.find(delimiter, pos_start)) != string::npos) {
        token = s.substr(pos_start, pos_end - pos_start);
        pos_start = pos_end + delim_len;
        res.push_back(token);
    }

    res.push_back(s.substr(pos_start));
    return res;
}

class Solution {
   public:
    bool isCircularSentence(string s) {
        vector<string> v = split(s, " ");
        int n = v.size();
        for (int i = 0; i < n; i++) {
            auto s1 = v[i];
            auto s2 = v[(i + 1) % n];

            if (s1.back() != s2[0]) {
                return false;
            }
        }
        return true;
    }
};