/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

#ifdef LOCAL
#define debug(...) cerr << "[" << #__VA_ARGS__ << "]:", debug_out(__VA_ARGS__)
#else
#define debug(...) 42
#endif

class Solution {
   public:
    int reachableNodes(int n, vector<vector<int>>& e, vector<int>& r) {
        vector<vector<int>> V(n);

        int m = e.size();
        for (int i = 0; i < m; i++) {
            int u = e[i][0], v = e[i][1];
            V[u].push_back(v);
            V[v].push_back(u);
        }

        vector<bool> vis(n);
        for (auto v : r) {
            vis[v] = 1;
        }

        int res = 0;
        function<void(int, int)> dfs = [&](int u, int pre) {
            res++;
            for (auto v : V[u]) {
                if (vis[v]) continue;
                if (v == pre) continue;
                dfs(v, u);
            }
        };
        dfs(0, -1);
        return res;
    }
};