/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

#ifdef LOCAL
#define debug(...) cerr << "[" << #__VA_ARGS__ << "]:", debug_out(__VA_ARGS__)
#else
#define debug(...) 42
#endif

class Solution {
   public:
    vector<int> numberOfPairs(vector<int>& nums) {
        map<int, int> M;
        int n = nums.size();
        for (int i = 0; i < n; i++) {
            M[nums[i]]++;
        }

        int a = 0, b = 0;
        for (auto it : M) {
            a += it.second / 2;
            b += it.second % 2;
        }

        return {a, b};

    }
};