/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

#ifdef LOCAL
#define debug(...) cerr << "[" << #__VA_ARGS__ << "]:", debug_out(__VA_ARGS__)
#else
#define debug(...) 42
#endif

class Solution {
   public:
    int appendCharacters(string s, string t) {
        int n = s.size();
        int m = t.size();

        int t_idx = 0;
        int s_idx = 0;

        while (t_idx < m) {
            while (s_idx < n && s[s_idx] != t[t_idx]) {
                s_idx++;
            }
            if (s_idx == n) break;
            t_idx++;
            if (t_idx == m) {
                break;
            }
        }
        return m - t_idx;
    }
};