/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

#ifdef LOCAL
#define debug(...) cerr << "[" << #__VA_ARGS__ << "]:", debug_out(__VA_ARGS__)
#else
#define debug(...) 42
#endif

class Solution {
   public:
    int minimumNumbers(int num, int k) {
        if (num == 0) {
            return 0;
        }

        for (int i = 1; i <= 10 && k * i <= num; i++) {
            if (k * i % 10 == num % 10) {
                return i;
            }
        }
        return -1;
    }
};