/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

class Solution {
   public:
    vector<int> maximumBobPoints(int numArrows, vector<int>& aliceArrows) {
        int n = 12;
        int LIMIT = 1 << n;

        vector<int> res;
        res.resize(n);
        int score = -1;
        for (int i = 1; i < LIMIT; i++) {
            int need = 0;
            int tmp = 0;
            for (int j = 0; j < n; j++) {
                if ((i >> j) & 1) {
                    need += aliceArrows[j] + 1;
                    tmp += j;
                }
            }
            if (need <= numArrows) {
                if (score < tmp) {
                    score = tmp;

                    for (int j = 0; j < n; j++) {
                        if ((i >> j) & 1) {
                            res[j] = aliceArrows[j] + 1;
                        } else {
                            res[j] = 0;
                        }
                    }
                    res[11] += (numArrows - need);
                }
            }
        }
        debug(score);
        return res;
    }
};