/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

class Solution {
   public:
    vector<int> intersection(vector<vector<int>>& nums) {
        int n = nums.size();

        map<int, int> M;
        for (int i = 0; i < n; i++) {
            for (int j = 0; j < nums[i].size(); j++) {
                M[nums[i][j]]++;
            }
        }
        vector<int> ans;
        for (auto it : M) {
            if (it.second == n) {
                ans.push_back(it.first);
            }
        }
        return ans;
    }
};