/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

class Solution {
   public:
    vector<vector<int>> findWinners(vector<vector<int>>& matches) {
        vector<vector<int>> ans;
        ans.resize(2);
        int n = matches.size();
        set<int> per;
        map<int, int> M;
        for (int i = 0; i < n; i++) {
            int a = matches[i][0], b = matches[i][1];
            M[b]++;
            per.insert(a);
            per.insert(b);
        }
        for (auto it : per) {
            int cnt = M[it];
            if (cnt == 0) {
                ans[0].push_back(it);
            } else if (cnt == 1) {
                ans[1].push_back(it);
            }
        }
        return ans;
    }
};