/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

class Encrypter {
   public:
    map<char, string> M;
    map<string, int> M2;

    Encrypter(vector<char>& keys, vector<string>& values, vector<string>& dictionary) {
        int n = keys.size();
        for (int i = 0; i < n; i++) {
            M[keys[i]] = values[i];
        }

        int m = dictionary.size();
        for (int i = 0; i < m; i++) {
            string it = encrypt(dictionary[i]);
            M2[it]++;
        }
    }

    string encrypt(string word1) {
        string ans = "";
        for (int i = 0; i < word1.size(); i++) {
            string tmp = M[word1[i]];
            ans += tmp;
        }
        return ans;
    }

    int decrypt(string word2) {
        return M2[word2];
    }
};

/**
 * Your Encrypter object will be instantiated and called as such:
 * Encrypter* obj = new Encrypter(keys, values, dictionary);
 * string param_1 = obj->encrypt(word1);
 * int param_2 = obj->decrypt(word2);
 */