/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

class Solution {
   public:
    string digitSum(string s, int k) {
        while (s.size() > k) {
            int n = s.size();
            vector<int> v(n);
            for (int i = 0; i < s.size(); i++) {
                v[i] = s[i] - '0';
            }
            vector<int> new_v;

            int now = 0;
            n = v.size();
            while (now < n) {
                int go = min(n, now + k);
                int val = 0;
                for (int i = now; i < go; i++) {
                    val += v[i];
                }
                new_v.push_back(val);
                now = go;
            }
            string res = "";
            for (int i = 0; i < new_v.size(); i++) {
                res += to_string(new_v[i]);
            }
            s = res;
        }
        return s;
    }
};