/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

class Solution {
   public:
    long long waysToBuyPensPencils(int total, int cost1, int cost2) {
        long long ans = 0;
        for (int i = 0; i * cost1 <= total; i++) {
            int left = total - i * cost1;
            int tmp = left / cost2;
            ans += tmp + 1;
        }
        return ans;
    }
};