/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

class Solution {
   public:
    int minimumCardPickup(vector<int>& cards) {
        map<int, int> M;
        int n = cards.size();
        int ans = n + 10;
        for (int i = 0; i < n; i++) {
            int val = cards[i];
            if (M.count(val)) {
                ans = min(ans, i - M[val] + 1);
            }
            M[val] = i;
        }
        if (ans == n + 10) ans = -1;
        return ans;
    }
};