/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

#ifdef LOCAL
#define debug(...) cerr << "[" << #__VA_ARGS__ << "]:", debug_out(__VA_ARGS__)
#else
#define debug(...) 42
#endif

class Solution {
   public:
    int pivotInteger(int n) {
        int sum = (1 + n) * n / 2;
        for (int i = 1; i <= n; i++) {
            int sum2 = (1 + i) * i / 2;
            int sum3 = (1 + i - 1) * (i - 1) / 2;

            if (sum2 == sum - sum3) {
                return i;
            }
        }
        return -1;
    }
};