/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

class Solution {
   public:
    int maximumCandies(vector<int>& candies, long long k) {
        int n = candies.size();
        long long sum = 0;
        for (int i = 0; i < n; i++) {
            sum += candies[i];
        }
        if (k > sum) {
            return 0;
        }
        long long l = 1, r = sum / k;
        long long ans = -1;
        auto check = [&](long long val) {
            int cnt = 0;
            for (int i = 0; i < n; i++) {
                cnt += candies[i] / val;
            }
            return cnt >= k;
        };

        while (l <= r) {
            long long mid = l + r >> 1;
            if (check(mid)) {
                ans = mid;
                l = mid + 1;
            } else {
                r = mid - 1;
            }
        }
        return ans;
    }
};