/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

class Solution {
   public:
    vector<int> work(int val) {
        vector<int> ans;
        while (val) {
            ans.push_back(val % 2);
            val /= 2;
        }
        return ans;
    }

    int minBitFlips(int start, int goal) {
        auto it = work(start);
        auto it2 = work(goal);
        int sz = max(it.size(), it2.size());
        it.resize(sz);
        it2.resize(sz);
        int ans = 0;
        for (int i = 0; i < sz; i++) {
            if (it[i] != it2[i]) ans++;
        }
        return ans;
    }
};