/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

class Solution {
   public:
    int countHillValley(vector<int>& nums) {
        int n = nums.size();

        int now = 0;
        int res = 0;
        while (now < n) {
            int go = now;
            while (go < n && nums[go] == nums[now]) {
                go++;
            }

            int l = -1, r = -1;
            if (now != 0) {
                l = nums[now - 1];
            }
            if (go != n) {
                r = nums[go];
            }
            if (l != -1 && r != -1) {
                if (l > nums[now] && r > nums[now]) {
                    res++;
                } else if (l < nums[now] && r < nums[now]) {
                    res++;
                }
            }

            now = go;
        }
        return res;
    }
};