/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

#ifdef LOCAL
#define debug(...) cerr << "[" << #__VA_ARGS__ << "]:", debug_out(__VA_ARGS__)
#else
#define debug(...) 42
#endif

typedef pair<string, int> psi;
class Solution {
   public:
    vector<int> smallestTrimmedNumbers(vector<string>& nums, vector<vector<int>>& q) {
        int n = nums.size();
        int m = q.size();

        int sz = nums[0].size();
        vector<psi> now(n);
        vector<int> ans(m);
        for (int i = 0; i < m; i++) {
            int rk = q[i][0], len = q[i][1];
            for (int j = 0; j < n; j++) {
                string it = nums[j].substr(sz - len, len);
                now[j] = {it, j};
            }
            sort(now.begin(), now.end());
            ans[i] = now[rk - 1].second;
        }
        return ans;
    }
};