/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

#ifdef LOCAL
#define debug(...) cerr << "[" << #__VA_ARGS__ << "]:", debug_out(__VA_ARGS__)
#else
#define debug(...) 42
#endif

class Solution {
   public:
    int maximumSum(vector<int>& nums) {
        vector<vector<int>> V(1000);
        int n = nums.size();
        for (int i = 0; i < n; i++) {
            int val = nums[i];
            int cnt = 0;
            while (val) {
                cnt += val % 10;
                val /= 10;
            }
            V[cnt].push_back(nums[i]);
        }

        int ans = -1;
        for (int i = 1; i < 1000; i++) {
            if (V[i].size() >= 2) {
                int sz = V[i].size();
                sort(V[i].begin(), V[i].end());
                ans = max(ans, V[i][sz - 1] + V[i][sz - 2]);
            }
        }
        return ans;
    }
};