/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

typedef pair<int, int> pii;
class Solution {
   public:
    vector<int> countRectangles(vector<vector<int>>& rec, vector<vector<int>>& p) {
        int q = p.size();
        vector<int> ans(q);
        int n = rec.size();
        vector<pii> v(n);
        for (int i = 0; i < n; i++) {
            v[i] = {rec[i][0], rec[i][1]};
        }
        sort(v.begin(), v.end());
        vector<int> f(q);
        iota(f.begin(), f.end(), 0);
        sort(f.begin(), f.end(), [&](int a, int b) {
            return p[a][0] > p[b][0];
        });

        int now = n - 1;
        vector<int> sum(101, 0);
        for (int i = 0; i < q; i++) {
            int idx = f[i];
            auto point = p[idx];
            int x = point[0], y = point[1];

            while (now >= 0 && v[now].first >= x) {
                int the_y = v[now].second;
                sum[the_y]++;
                now--;
            }

            int tmp = 0;
            for (int j = y; j <= 100; j++) {
                tmp += sum[j];
            }
            ans[idx] = tmp;
        }
        return ans;
    }
};