/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

class Solution {
   public:
    int largestInteger(int num) {
        vector<int> v[2];
        int a = num;
        vector<int> V;
        while (num) {
            V.push_back(num % 10);
            v[num % 10 % 2].push_back(num % 10);
            num /= 10;
        }
        sort(v[0].begin(), v[0].end());
        sort(v[1].begin(), v[1].end());

        int res = 0;
        int a_idx = v[0].size() - 1, b_idx = v[1].size() - 1;
        for (int i = V.size() - 1; i >= 0; i--) {
            if (V[i] % 2) {
                res = res * 10 + v[1][b_idx];
                b_idx--;
            } else {
                res = res * 10 + v[0][a_idx];
                a_idx--;
            }
        }
        return res;
    }
};