/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

#ifdef LOCAL
#define debug(...) cerr << "[" << #__VA_ARGS__ << "]:", debug_out(__VA_ARGS__)
#else
#define debug(...) 42
#endif

class Solution {
   public:
    int edgeScore(vector<int>& e) {
        int n = e.size();

        vector<int> val(n);
        for (int i = 0; i < n; i++) {
            val[e[i]] += i;
        }

        int mx_idx = 0;
        for (int i = 1; i < n; i++) {
            if (val[i] > val[mx_idx]) {
                mx_idx = i;
            }
        }
        return mx_idx;
    }
};