/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

class Solution {
   public:
    int convertTime(string current, string correct) {
        auto work = [&](string s) -> int {
            int a = (s[0] - '0') * 10 + (s[1] - '0');
            int b = (s[3] - '0') * 10 + (s[4] - '0');
            return a * 60 + b;
        };
        int flag = 24 * 60;

        int a = work(current);
        int b = work(correct);
        int ct = b - a;
        if (ct < 0) {
            ct += flag;
        }

        vector<int> V = {60, 15, 5, 1};
        int ans = 0;
        for (int i = 0; i < V.size(); i++) {
            int tmp = ct / V[i];
            ans += tmp;
            ct %= V[i];
        }
        return ans;
    }
};