/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

#ifdef LOCAL
#define debug(...) cerr << "[" << #__VA_ARGS__ << "]:", debug_out(__VA_ARGS__)
#else
#define debug(...) 42
#endif

class Solution {
   public:
    int minNumberOfHours(int a, int b, vector<int>& energy, vector<int>& experience) {
        int sum = 0;
        int n = energy.size();
        for (int i = 0; i < n; i++) {
            sum += energy[i];
        }
        int res = max(0, sum + 1 - a);
        int needb = 0;
        int sumb = 0;
        debug(res);
        for (int i = 0; i < n; i++) {
            needb = max(needb, experience[i] + 1 - sumb);
            sumb += experience[i];
        }
        res += max(0, needb - b);
        return res;
    }
};