/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

class Solution {
   public:
    vector<int> findKDistantIndices(vector<int>& nums, int key, int k) {
        vector<int> ans;
        int n = nums.size();
        for (int i = 0; i < n; i++) {
            bool f = false;
            for (int j = i - k; j <= i + k; j++) {
                if (j >= 0 && j < n && nums[j] == key) {
                    f = true;
                    break;
                }
            }
            if (f) {
                ans.push_back(i);
            }
        }
        return ans;
    }
};