/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

#ifdef LOCAL
#define debug(...) cerr << "[" << #__VA_ARGS__ << "]:", debug_out(__VA_ARGS__)
#else
#define debug(...) 42
#endif

class Solution {
   public:
    bool validPartition(vector<int>& a) {
        int n = a.size();

        vector<int> dp(n + 1, 0);
        dp[0] = 1;

        for (int i = 2; i <= n; i++) {
            int val = a[i - 1];
            int val2 = a[i - 2];
            if (val == val2) {
                dp[i] |= dp[i - 2];
            }
            if (i >= 3) {
                int val3 = a[i - 3];
                if (val == val2 && val == val3) {
                    dp[i] |= dp[i - 3];
                }
                if (val - 1 == val2 && val2 - 1 == val3) {
                    dp[i] |= dp[i - 3];
                }
            }
        }
        debug(dp);
        return dp[n] == 1;
    }
};