/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

int a[5] = {20, 50, 100, 200, 500};

class ATM {
   public:
    map<int, int> M;
    ATM() {
        M.clear();
    }
    void deposit(vector<int> banknotesCount) {
        int n = 5;
        for (int i = 0; i < n; i++) {
            M[a[i]] += banknotesCount[i];
        }
    }

    vector<int> withdraw(int amount) {
        vector<int> ans(5);
        map<int, int> M2 = M;

        for (int i = 4; i >= 0; i--) {
            int need = min(M2[a[i]], amount / a[i]);
            M2[a[i]] -= need;
            amount -= need * a[i];
            ans[i] = need;
        }
        if (amount != 0) {
            return {-1};
        }
        M = M2;
        return ans;
    }
};

/**
 * Your ATM object will be instantiated and called as such:
 * ATM* obj = new ATM();
 * obj->deposit(banknotesCount);
 * vector<int> param_2 = obj->withdraw(amount);
 */