/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

#ifdef LOCAL
#define debug(...) cerr << "[" << #__VA_ARGS__ << "]:", debug_out(__VA_ARGS__)
#else
#define debug(...) 42
#endif

class Solution {
   public:
    int deleteGreatestValue(vector<vector<int>>& g) {
        int n = g.size();
        int m = g[0].size();

        for (int i = 0; i < n; i++) {
            sort(g[i].rbegin(), g[i].rend());
        }
        int ans = 0;
        for (int i = 0; i < m; i++) {
            int mx = -1;
            for (int j = 0; j < n; j++) {
                mx = max(g[j][i], mx);
            }
            ans += mx;
        }
        return ans;
    }
};