/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

#ifdef LOCAL
#define debug(...) cerr << "[" << #__VA_ARGS__ << "]:", debug_out(__VA_ARGS__)
#else
#define debug(...) 42
#endif

class Solution {
   public:
    string decodeMessage(string key, string message) {
        map<char, char> M;

        int flag = 0;
        for (int i = 0; i < key.size(); i++) {
            if (key[i] == ' ' || M.count(key[i])) {
                continue;
            }
            M[key[i]] = 'a' + flag;
            flag++;
        }

        string ans = "";
        for (int i = 0; i < message.size(); i++) {
            if (message[i] == ' ') {
                ans.push_back(' ');
            } else {
                ans.push_back(M[message[i]]);
            }
        }
        return ans;
    }
};