/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

#ifdef LOCAL
#define debug(...) cerr << "[" << #__VA_ARGS__ << "]:", debug_out(__VA_ARGS__)
#else
#define debug(...) 42
#endif

class Solution {
   public:
    int fillCups(vector<int>& a) {
        int ans = 0;
        multiset<int> S;
        for (auto it : a) {
            if (it > 0)
                S.insert(it);
        }

        while (S.size()) {
            if (S.size() == 1) {
                ans += *S.begin();
                break;
            }

            int tmp1 = *S.rbegin();
            S.erase(prev(S.end()));
            int tmp2 = *S.rbegin();
            S.erase(prev(S.end()));
            tmp1--, tmp2--;
            if (tmp1) {
                S.insert(tmp1);
            }
            if (tmp2) {
                S.insert(tmp2);
            }
            ans += 1;
        }
        return ans;
    }
};