/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif
const int maxn = 1e5 + 5;

class Solution {
   public:
    long long appealSum(string s) {
        long long ans = 0;
        int n = s.size();

        for (int i = 0; i < 26; i++) {
            int lst = 0;
            ans += n * (n + 1);
            for (int j = 0; j < n; j++) {
                if (s[j] - 'a' == i) {
                    long long num = j - lst;
                    ans -= num * (num + 1);
                    lst = j + 1;
                }
            }
            long long num = n - lst;
            ans -= num * (num + 1);
        }
        return ans >> 1;
    }
};