/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

#ifdef LOCAL
#define debug(...) cerr << "[" << #__VA_ARGS__ << "]:", debug_out(__VA_ARGS__)
#else
#define debug(...) 42
#endif

class Solution {
   public:
    int countSubarrays(vector<int>& nums, int k) {
                int n = nums.size();

        int idx = -1;
        vector<int> sum(n + 1);

        for (int i = 1; i <= n; i++) {
            sum[i] = sum[i - 1];
            int val = nums[i - 1];
            if (val == k) {
                idx = i;
            } else if (val < k) {
                sum[i] += -1;
            } else {
                sum[i] += 1;
            }
        }

        map<int, int> M;
        for (int i = idx; i <= n; i++) {
            M[sum[i]]++;
        }

        int ans = 0;
        for (int i = idx; i >= 1; i--) {
            int val = sum[i - 1];
            // sum = 0 | 1
            ans += M[val];
            ans += M[val + 1];
        }
        return ans;
    }
};