/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

class Solution {
   public:
    int triangularSum(vector<int>& nums) {
        int n = nums.size();
        vector<vector<int>> ans;
        ans.resize(2, vector<int>(n));
        for (int i = 0; i < n; i++) {
            ans[0][i] = nums[i];
        }
        bool f = 0;
        while (n != 1) {
            bool f2 = f ^ 1;
            for (int i = 0; i < ans[f].size() - 1; i++) {
                ans[f2][i] = (ans[f][i] + ans[f][i + 1]) % 10;
            }
            ans[f2].resize(ans[f].size() - 1);
            // debug(ans[f2]);
            f = f2;
            n--;
        }
        return ans[f][0];
    }
};