/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

class Solution {
   public:
    int countCollisions(string directions) {
        int n = directions.size();
        int now = 0;
        int res = 0;
        while (now < n) {
            int go = now;
            while (go < n && directions[go] == directions[now]) {
                go++;
            }
            if (directions[now] == 'S') {
            } else if (directions[now] == 'L') {
                if (now != 0) {
                    if (directions[now - 1] == 'R') {
                        res += (go - now - 1);
                    } else {
                        res += (go - now);
                    }
                }
            } else if (directions[now] == 'R') {
                if (go != n) {
                    if (directions[go] == 'S') {
                        res += (go - now);
                    } else {
                        res += (go - now + 1);
                    }
                }
            }
            now = go;
        }
        return res;
    }
};