/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

#ifdef LOCAL
#define debug(...) cerr << "[" << #__VA_ARGS__ << "]:", debug_out(__VA_ARGS__)
#else
#define debug(...) 42
#endif

class Solution {
   public:
    int longestIdealString(string s, int k) {
        int n = s.size();
        vector<int> dp(n + 1);
        vector<int> last(26, -1);
        int res = 0;
        for (int i = 1; i <= n; i++) {
            int now = s[i - 1] - 'a';
            int mi = max(0, now - k);
            int mx = min(25, now + k);
            dp[i] = 1;
            for (int j = mi; j <= mx; j++) {
                if (last[j] != -1) {
                    dp[i] = max(dp[i], dp[last[j]] + 1);
                }
            }
            res = max(res, dp[i]);
            last[now] = i;
        }
        debug(dp);
        return res;
    }
};