/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

#ifdef LOCAL
#define debug(...) cerr << "[" << #__VA_ARGS__ << "]:", debug_out(__VA_ARGS__)
#else
#define debug(...) 42
#endif

class Solution {
   public:
    int garbageCollection(vector<string>& g, vector<int>& t) {
        int n = g.size();
        vector<map<char, int>> V(n);

        for (int i = 0; i < n; i++) {
            int m = g[i].size();
            for (int j = 0; j < m; j++) {
                V[i][g[i][j]]++;
            }
        }

        auto work = [&](char it) -> long long {
            int last_idx = n;
            for (int i = n - 1; i >= 0; i--) {
                if (V[i][it] == 0) {
                    last_idx = i;
                } else {
                    break;
                }
            }

            long long ans = 0;
            for (int i = 0; i < last_idx; i++) {
                int num = V[i][it];
                ans += num;
                if (i != last_idx - 1) {
                    ans += t[i];
                }
            }
            return ans;
        };

        long long ans = 0;
        ans += work('M') + work('P') + work('G');
        return ans;
    }
};