/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

#ifdef LOCAL
#define debug(...) cerr << "[" << #__VA_ARGS__ << "]:", debug_out(__VA_ARGS__)
#else
#define debug(...) 42
#endif

class Solution {
   public:
    vector<int> cycleLengthQueries(int n, vector<vector<int>>& queries) {
        int m = queries.size();

        vector<int> ans(m);
        for (int i = 0; i < m; i++) {
            int u = queries[i][0], v = queries[i][1];

            int a = 0, b = 0;
            while (u != v) {
                if (u < v) {
                    b++;
                    v = v / 2;
                } else {
                    a++;
                    u = u / 2;
                }
            }
            ans[i] = a + b + 1;
        }
        return ans;
    }
};