/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

#ifdef LOCAL
#define debug(...) cerr << "[" << #__VA_ARGS__ << "]:", debug_out(__VA_ARGS__)
#else
#define debug(...) 42
#endif

class Solution {
   public:
    vector<vector<string>> mostPopularCreator(vector<string>& creators, vector<string>& ids, vector<int>& views) {
        int n = creators.size();
        map<string, long long> M;
        map<string, vector<int>> M2;
        long long mx = 0;
        for (int i = 0; i < n; i++) {
            int v = views[i];
            M[creators[i]] += v;
            M2[creators[i]].push_back(i);
            mx = max(mx, M[creators[i]]);
        }

        vector<vector<string>> ans;

        auto work = [&](string s) -> string {
            int res = -1;
            string ans = "";
            for (auto it : M2[s]) {
                if (views[it] > res) {
                    ans = ids[it];
                    res = views[it];
                } else if (views[it] == res && ans > ids[it]) {
                    ans = ids[it];
                }
            }
            return ans;
        };

        for (auto it : M) {
            if (it.second == mx) {
                vector<string> subans = {it.first, work(it.first)};
                ans.push_back(subans);
            }
        }
        return ans;
    }
};