/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

#ifdef LOCAL
#define debug(...) cerr << "[" << #__VA_ARGS__ << "]:", debug_out(__VA_ARGS__)
#else
#define debug(...) 42
#endif

class Solution {
   public:
    int closetTarget(vector<string>& words, string target, int x) {
        int idx = -1;
        int res = 1e9;
        int n = words.size();
        for (int i = 0; i < n; i++) {
            if (words[i] == target) {
                idx = i;
                res = min({res, abs(x - i), n - abs(x - i)});
            }
        }
        if (res == 1e9) res = -1;
        return res;
    }
};