/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

class Solution {
   public:
    int maximumTop(vector<int>& nums, int k) {
        int n = nums.size();
        if (n == 1) {
            if (k % 2) {
                return -1;
            } else {
                return nums[0];
            }
        }
        int mx = -1;
        for (int i = 0; i < n; i++) {
            mx = max(mx, nums[i]);
        }

        if (n < k) {
            return mx;
        }
        mx = -1;
        for (int i = 0; i < k - 1; i++) {
            mx = max(mx, nums[i]);
        }

        if (k < n) {
            mx = max(mx, nums[k]);
        }

        return mx;
    }
};