/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

#ifdef LOCAL
#define debug(...) cerr << "[" << #__VA_ARGS__ << "]:", debug_out(__VA_ARGS__)
#else
#define debug(...) 42
#endif

class Solution {
   public:
    int minimumPartition(string s, int k) {
        int n = s.size();
        int idx = 0;
        int res = 0;
        while (idx < n) {
            res++;
            long long it = s[idx] - '0';
            if (it > k) return -1;
            int go = idx + 1;
            while (it <= k) {
                if (go >= n) break;
                int x = s[go] - '0';
                long long tmp = it * 10 + x;
                if (tmp <= k) {
                    it = tmp;
                    go++;
                } else {
                    break;
                }
            }
            idx = go;
        }
        return res;
    }
};