/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

#ifdef LOCAL
#define debug(...) cerr << "[" << #__VA_ARGS__ << "]:", debug_out(__VA_ARGS__)
#else
#define debug(...) 42
#endif

class Solution {
   public:
    string largestPalindromic(string num) {
        int n = num.size();

        vector<int> val(10);
        for (int i = 0; i < n; i++) {
            val[num[i] - '0']++;
        }
        debug(val);
        string s1 = "", s2 = "";
        bool flag = false;
        for (int i = 9; i >= 1; i--) {
            if (val[i] > 1) {
                int tmp = val[i] / 2;
                for (int j = 0; j < tmp; j++) {
                    s1 += ('0' + i);
                    s2 += ('0' + i);
                }
                val[i] -= tmp * 2;
                flag = true;
            }
        }

        if (flag) {
            int tmp = val[0] / 2;
            for (int j = 0; j < tmp; j++) {
                s1 += '0';
                s2 += '0';
            }
            val[0] -= tmp * 2;
        }
        for (int i = 9; i >= 0; i--) {
            if (val[i]) {
                s1 += ('0' + i);
                break;
            }
        }
        reverse(s2.begin(), s2.end());
        string res = s1 + s2;
        return res;
    }
};