/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

class Solution {
   public:
    int minDeletion(vector<int>& nums) {
        int n = nums.size();
        int now = 0;

        vector<int> ans;

        while (now < n) {
            int go = now;
            while (go < n && nums[go] == nums[now]) {
                go++;
            }
            if (go < n) {
                ans.push_back(nums[now]);
                ans.push_back(nums[go]);
            }
            now = go + 1;
        }
        return nums.size() - ans.size();
    }
};