/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

#ifdef LOCAL
#define debug(...) cerr << "[" << #__VA_ARGS__ << "]:", debug_out(__VA_ARGS__)
#else
#define debug(...) 42
#endif

class Solution {
   public:
    int distinctPrimeFactors(vector<int>& nums) {
        set<int> S;
        int n = nums.size();

        auto work = [&](int val) {
            for (int i = 2; i * i <= val; i++) {
                if (val % i == 0) {
                    S.insert(i);
                    while (val % i == 0) {
                        val /= i;
                    }
                }
            }
            if (val != 1) {
                S.insert(val);
            }
        };

        for (int i = 0; i < n; i++) {
            int val = nums[i];
            work(val);
        }
        return S.size();
    }
};