/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

#ifdef LOCAL
#define debug(...) cerr << "[" << #__VA_ARGS__ << "]:", debug_out(__VA_ARGS__)
#else
#define debug(...) 42
#endif

typedef long long ll;
class Solution {
   public:
    int longestSubsequence(string s, int k) {
        int n = s.size();

        ll now = 0;
        int cnt = 0;
        int res = 0;
        for (int i = n - 1; i >= 0; i--) {
            int it = s[i] - '0';
            if (it == 0) {
                res++;
                cnt++;
            } else {
                if (cnt >= 32) continue;
                ll tmp = (1LL << cnt) + now;
                if (tmp <= k) {
                    res++;
                    now = tmp;
                    cnt++;
                }
            }
        }
        return res;
    }
};