/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

#ifdef LOCAL
#define debug(...) cerr << "[" << #__VA_ARGS__ << "]:", debug_out(__VA_ARGS__)
#else
#define debug(...) 42
#endif

typedef pair<int, int> pii;
class Solution {
   public:
    int minimumLines(vector<vector<int>>& s) {
        int n = s.size();
        if (n <= 2) {
            return 1;
        }
        vector<pii> V;
        for (int i = 0; i < n; i++) {
            V.push_back({s[i][0], s[i][1]});
        }
        sort(V.begin(), V.end());

        pii last1 = V[0], last2 = V[1];
        int ans = 1;
        for (int i = 2; i < n; i++) {
            pii now = V[i];
            if (1LL * (now.second - last2.second) * (last2.first - last1.first) == 1LL * (last2.second - last1.second) * (now.first - last2.first)) {
            } else {
                ans++;
            }
            last1 = last2;
            last2 = now;
        }
        return ans;
    }
};