/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

#ifdef LOCAL
#define debug(...) cerr << "[" << #__VA_ARGS__ << "]:", debug_out(__VA_ARGS__)
#else
#define debug(...) 42
#endif

class Solution {
   public:
    string largestGoodInteger(string num) {
        int n = num.size();

        string ans = "";
        for (int i = 0; i < n; i++) {
            char it = num[i];
            string tmp = "";
            bool flag = true;
            for (int j = 0; j < 3; j++) {
                if (i + j < n && num[i + j] == it) {
                    tmp += num[i + j];
                } else {
                    flag = false;
                }
            }
            if (flag) {
                ans = max(ans, tmp);
            }
        }
        return ans;
    }
};