/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

#ifdef LOCAL
#define debug(...) cerr << "[" << #__VA_ARGS__ << "]:", debug_out(__VA_ARGS__)
#else
#define debug(...) 42
#endif

class Solution {
   public:
    vector<string> removeAnagrams(vector<string>& words) {
        int n = words.size();
        vector<string> s2 = words;
        for (int i = 0; i < n; i++) {
            sort(s2[i].begin(), s2[i].end());
        }

        set<string> S;
        vector<string> ans;
        int last_idx = -1;
        for (int i = 0; i < n; i++) {
            if (last_idx == -1 || s2[last_idx] != s2[i]) {
                ans.push_back(words[i]);
                last_idx = i;
            }
        }
        return ans;
    }
};