/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

#ifdef LOCAL
#define debug(...) cerr << "[" << #__VA_ARGS__ << "]:", debug_out(__VA_ARGS__)
#else
#define debug(...) 42
#endif

class Solution {
   public:
    long long work(vector<int>& num1, vector<int>& num2) {
        int n = num1.size();
        long long sum1 = 0, sum2 = 0;
        vector<long long> sum(n + 1);
        for (int i = 1; i <= n; i++) {
            sum1 += num1[i - 1];
            sum2 += num2[i - 1];
            sum[i] = sum2 - sum1;
        }

        long long ans = 0;
        long long mi = 0;
        for (int i = 1; i <= n; i++) {
            ans = max(ans, sum[i] - mi);
            mi = min(mi, sum[i]);
        }
        return ans + sum1;
    }

    int maximumsSplicedArray(vector<int>& nums1, vector<int>& nums2) {
        int n = nums1.size();

        long long ans = work(nums1, nums2);
        ans = max(ans, work(nums2, nums1));
        return ans;
    }
};