/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

#ifdef LOCAL
#define debug(...) cerr << "[" << #__VA_ARGS__ << "]:", debug_out(__VA_ARGS__)
#else
#define debug(...) 42
#endif

class Solution {
   public:
    int maxConsecutive(int bottom, int top, vector<int>& s) {
        s.push_back(top + 1);
        int n = s.size();
        sort(s.begin(), s.end());
        int L = bottom;
        int ans = 0;

        for (int i = 0; i < n; i++) {
            int v = s[i];
            ans = max(ans, v - L);
            L = v + 1;
        }
        return ans;
    }
};