/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

#ifdef LOCAL
#define debug(...) cerr << "[" << #__VA_ARGS__ << "]:", debug_out(__VA_ARGS__)
#else
#define debug(...) 42
#endif

class Solution {
   public:
    long long distinctNames(vector<string>& ideas) {
        sort(ideas.begin(), ideas.end());
        ideas.resize(unique(ideas.begin(), ideas.end()) - ideas.begin());
        vector<vector<int>> like = vector(26, vector(26, 0));
        int n = ideas.size();

        unordered_set<string> S;
        for (int i = 0; i < n; i++) {
            S.insert(ideas[i]);
        }

        for (int i = 0; i < n; i++) {
            string it = ideas[i];
            char beg = it[0];
            for (int j = 0; j < 26; j++) {
                it[0] = 'a' + j;
                if (S.count(it)) continue;
                like[ideas[i][0] - 'a'][j]++;
                it[0] = beg;
            }
        }

        long long ans = 0;
        for (int i = 0; i < n; i++) {
            string it = ideas[i];
            char beg = it[0];
            for (int j = 0; j < 26; j++) {
                it[0] = 'a' + j;
                if (S.count(it)) continue;
                // 它ok
                ans += like[j][beg - 'a'];
            }
        }
        return ans;
    }
};