/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

class Solution {
   public:
    vector<vector<int>> findDifference(vector<int>& nums1, vector<int>& nums2) {
        int n = nums1.size();
        int m = nums2.size();

        set<int> S1, S2;
        for (int i = 0; i < n; i++) {
            S1.insert(nums1[i]);
        }
        for (int i = 0; i < m; i++) {
            S2.insert(nums2[i]);
        }
        vector<vector<int>> ans(2);

        for (int i = 0; i < n; i++) {
            if (S2.count(nums1[i])) continue;
            S2.insert(nums1[i]);
            ans[0].push_back(nums1[i]);
        }
        for (int i = 0; i < m; i++) {
            if (S1.count(nums2[i])) continue;
            S1.insert(nums2[i]);
            ans[1].push_back(nums2[i]);
        }
        return ans;
    }
};