/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

#ifdef LOCAL
#define debug(...) cerr << "[" << #__VA_ARGS__ << "]:", debug_out(__VA_ARGS__)
#else
#define debug(...) 42
#endif

class SmallestInfiniteSet {
   public:
    set<int> S;
    SmallestInfiniteSet() {
        for (int i = 1; i <= 2000; i++) {
            S.insert(i);
        }
    }

    int popSmallest() {
        int it = *S.begin();
        S.erase(S.begin());
        return it;
    }

    void addBack(int num) {
        S.insert(num);
    }
};

/**
 * Your SmallestInfiniteSet object will be instantiated and called as such:
 * SmallestInfiniteSet* obj = new SmallestInfiniteSet();
 * int param_1 = obj->popSmallest();
 * obj->addBack(num);
 */