/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

#ifdef LOCAL
#define debug(...) cerr << "[" << #__VA_ARGS__ << "]:", debug_out(__VA_ARGS__)
#else
#define debug(...) 42
#endif

class Solution {
   public:
    long long makeSimilar(vector<int>& nums, vector<int>& target) {
        int n = nums.size();
        vector<int> v[2], v2[2];
        for (int i = 0; i < n; i++) {
            v[nums[i] % 2].push_back(nums[i]);
            v2[target[i] % 2].push_back(target[i]);
        }
        sort(v[0].begin(), v[0].end());
        sort(v2[0].begin(), v2[0].end());
        sort(v[1].begin(), v[1].end());
        sort(v2[1].begin(), v2[1].end());

        long long res = 0;
        int m = v[0].size();
        for (int i = 0; i < m; i++) {
            if (v[0][i] > v2[0][i]) {
                res += abs(v[0][i] - v2[0][i]) / 2;
            }
        }
        m = v[1].size();
        for (int i = 0; i < m; i++) {
            if (v[1][i] > v2[1][i]) {
                res += abs(v[1][i] - v2[1][i]) / 2;
            }
        }
        return res;
    }
};