/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

#ifdef LOCAL
#define debug(...) cerr << "[" << #__VA_ARGS__ << "]:", debug_out(__VA_ARGS__)
#else
#define debug(...) 42
#endif

class Solution {
   public:
    long long dividePlayers(vector<int>& v) {
        int n = v.size();
        sort(v.begin(), v.end());

        int val = v[0] + v[n - 1];
        long long ans = 0;
        for (int i = 0; i < n / 2; i++) {
            int i2 = n - 1 - i;
            int val2 = v[i] + v[i2];
            if (val != val2) {
                return -1;
            }
            ans += 1LL * v[i] * v[i2];
        }
        return ans;
    }
};