/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

class Solution {
   public:
    int countDistinct(vector<int>& nums, int k, int p) {
        int n = nums.size();
        set<vector<int>> S;
        for (int i = 0; i < n; i++) {
            vector<int> tmp;
            int now = 0;
            for (int j = i; j < n; j++) {
                if (nums[j] % p == 0) {
                    now++;
                    if (now > k) {
                        break;
                    }
                }
                tmp.push_back(nums[j]);
                S.insert(tmp);
            }
        }
        return S.size();
    }
};