/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

class Solution {
   public:
    long long maximumSubsequenceCount(string text, string pattern) {
        string s1 = pattern[0] + text;
        string s2 = text + pattern[1];

        auto work = [&](string &s) {
            int n = s.size();
            vector<int> sum;
            sum.resize(n);
            long long res = 0;

            for (int i = n - 1; i >= 0; i--) {
                if (i != n - 1) {
                    sum[i] += sum[i + 1];
                }
                if (s[i] == pattern[0]) {
                    res += sum[i];
                }
                if (s[i] == pattern[1]) {
                    sum[i]++;
                }
            }
            return res;
        };

        return max(work(s1), work(s2));
    }
};