/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

typedef pair<int, int> pii;
class Solution {
   public:
    vector<int> fullBloomFlowers(vector<vector<int>>& f, vector<int>& p) {
        vector<pii> event;
        int n = f.size();
        for (int i = 0; i < n; i++) {
            int l = f[i][0], r = f[i][1];
            event.push_back({l, 1});
            event.push_back({r + 1, -1});
        }
        int m = p.size();
        for (int i = 0; i < m; i++) {
            int x = p[i];
            event.push_back({x, i + 2});
        }
        sort(event.begin(), event.end());

        int e_num = event.size();
        int f_num = 0;
        vector<int> ans(m);
        for (int i = 0; i < e_num; i++) {
            auto it = event[i];
            if (it.second == 1) {
                f_num++;
            } else if (it.second == -1) {
                f_num--;
            } else {
                ans[it.second - 2] = f_num;
            }
        }
        return ans;
    }
};