/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

#ifdef LOCAL
#define debug(...) cerr << "[" << #__VA_ARGS__ << "]:", debug_out(__VA_ARGS__)
#else
#define debug(...) 42
#endif

class Solution {
   public:
    int similarPairs(vector<string>& words) {
        int n = words.size();
        int ans = 0;
        for (int i = 0; i < n; i++) {
            int m = words[i].size();
            vector<bool> vis(26);
            for (int j = 0; j < m; j++) {
                vis[words[i][j] - 'a'] = 1;
            }

            for (int j = i + 1; j < n; j++) {
                bool flag = true;

                int m2 = words[j].size();
                vector<bool> vis2(26);
                for (int k = 0; k < m2; k++) {
                    vis2[words[j][k] - 'a'] = 1;
                }

                for (int k = 0; k < 26; k++) {
                    if (vis[k] != vis2[k]) {
                        flag = false;
                        break;
                    }
                }

                if (flag) {
                    ans++;
                }
            }
        }
        return ans;
    }
};