/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

class Solution {
   public:
    int countLatticePoints(vector<vector<int>>& c) {
        int n = c.size();
        int res = 0;
        int ans = 0;

        auto check = [&](int x, int y) {
            for (int i = 0; i < n; i++) {
                int x1 = c[i][0], y1 = c[i][1], r = c[i][2];
                int _x = x1 - x;
                int _y = y1 - y;
                if (_x * _x + _y * _y <= r * r) return true;
            }
            return false;
        };

        for (int i = 0; i <= 200; i++) {
            for (int j = 0; j <= 200; j++) {
                if (check(i, j)) {
                    ans++;
                }
            }
        }
        return ans;
    }
};