/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

class Solution {
   public:
    int maximumProduct(vector<int>& nums, int k) {
        multiset<int> S;
        for (auto it : nums) {
            S.insert(it);
        }

        while (k--) {
            auto it = S.begin();
            int val = *it;
            S.erase(it);
            S.insert(val + 1);
        }
        const int mod = 1e9 + 7;
        long long ans = 1;
        for (auto it : S) {
            ans = ans * it % mod;
        }
        return ans;
    }
};