/*
Code generated by https://github.com/goodStudyTnT/leetcode-tester
*/

#if __has_include("../../utils/cpp/help.h")
#include "../../utils/cpp/help.h"
#endif

#ifdef LOCAL
#define debug(...) cerr << "[" << #__VA_ARGS__ << "]:", debug_out(__VA_ARGS__)
#else
#define debug(...) 42
#endif

class Solution {
   public:
    int minOperations(vector<int>& nums, vector<int>& d) {
        sort(nums.begin(), nums.end());

        int g = d[0];
        int m = d.size();
        for (int i = 1; i < m; i++) {
            g = __gcd(g, d[i]);
        }

        for (int i = 0; i < nums.size(); i++) {
            if (g % nums[i] == 0) {
                return i;
            }
        }
        return -1;
    }
};